import Config

# Configure connection to the Bitcoin Network:

# mainnet:
config :joy, magic: <<0xF9, 0xBE, 0xB4, 0xD9>>

# testnet/regtest:
# config :joy, magic: <<0xFA, 0xBF, 0xB5, 0xDA>>

config :joy,
  # ip: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0xFF, 127, 0, 0, 1>>
  # ip: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0xFF, 46, 101, 116, 88>>
  ip: <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0xFF, 3, 73, 204, 15>>

# config :joy, port: 19_444
# config :joy, port: 8332
config :joy, port: 48_333

# Configure your database
config :joy, Joy.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "joy_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :joy, JoyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    "rBl4Pfl8H1QbeQOeS87ysIgIRij3oAOUwjG0qZQ5VvHgMUzDyVowY0fQQ6rMUmmM",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :joy, JoyWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/joy_web/(components|controllers|live)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :joy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
